### ISSUE TITLE
dev-libs/amdgpu-pro-opencl-21.40.1.40501: broken download URL

### ISSUE THREAD

**Issue by Bogdan107** [inode64/inode64-overlay#1]
I have warning:
```
 * Please download Radeon Software for Linux version 21.40 for Ubuntu 20.04.3 from
 *     https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-21.40-1.40501
 * The archive should then be placed into your distfiles directory.
```
But URL has error **Page not found**.

Correct URL values from `dev-libs/amdgpu-pro-opencl::gentoo`:
- https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-30
- https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-21-30

Correct URL value from WWW search engine:
- https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-21-40-1

**Comment by inode64** [comment]
Thanks, I fix the problem in commit  #233e7bd7b0e34f97b2a7b881ea8d89f4b2b851c0 

I have also added the rocm-opencl-runtime update.
I have solved all the compilation problems but I kept getting coredumps when executing clinfo
But in the end I had to change the video card from radeon to nvidia because the davinci studio software did not work for me and I have not continued since I have spent many days without being able to solve the coredumps.

https://github.com/gentoo/gentoo/pull/23343
