### ISSUE TITLE
dev-util/phpstorm-2022.3.3:0/0 prevents openssl update

### ISSUE THREAD

**Issue by suharelli** [inode64/inode64-overlay#12]
`(dev-libs/openssl-3.0.9-r2:0/3::gentoo, ebuild scheduled for merge) USE="asm -fips -ktls -rfc3779 -sctp -static-libs -test -tls-compression -vanilla -verify-sig -weak-ssl-ciphers" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="(sse2)" conflicts with
    dev-libs/openssl:0/1.1= required by (dev-util/phpstorm-2022.3.3:0/0::inode64-overlay, installed) USE="" ABI_X86="(64)"`

**Comment by inode64** [comment]
Fix in [#a788c2114b9110e8f43449008ab9e73a0cfe1fc1](https://github.com/inode64/inode64-overlay/commit/a788c2114b9110e8f43449008ab9e73a0cfe1fc1)

**Comment by lkraav** [comment]
I'm not sure I understand: this fix doesn't enable installing PhpStorm with OpenSSL 3.

```
emerge: there are no binary packages to satisfy "<dev-libs/openssl-3.0".
(dependency required by "dev-util/phpstorm-2023.2.3::lkraav" [binary])
(dependency required by "phpstorm" [argument])
```

I can't find any information that says IDEA is not compatible with OpenSSL 3, do y'all know what the situation is?

Portage has a list of IDEA packages in the tree (CLion, PyCharm, etc) that have omitted any SSL `RDEPEND` atoms altogether. Is this the right move?

**Comment by inode64** [comment]
I was also researching it, and didn't see anything. but if you run lld /opt/phpstorm-2023.2.3/jbr/lib/jcef_helper, libcef.so and  libjcef.so  you will see that it uses openssl 1.1
```
libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f7156cd0000)
```

If you have, install the latest version of phpstorm 2023.2.3 and openssl 3.x run:
```
revdep-rebuild -v -i
```
to check that there are no broken libraries
At the moment I still use openssl 1.1 because I have a project in PHP 5.6 and 7.4 active
As a solution, if you use the system java, you can eliminate java included as idea-community, but that eliminates improvements such as fonts (https://www.jetbrains.com/lp/mono/) and some customizations, but I have not found the post about what changed about the java baseline

**Comment by inode64** [comment]
I found a solution to move to PHP 5.4 and 7.4 with OPENSSL 3.x
https://github.com/internethering/hering-overlay
If possible this weekend I'll try it

**Comment by inode64** [comment]
I have included php 5.6 and 7.4 support for openssl 3.x, but I haven't fully tested it yet

**Comment by inode64** [comment]
This is Java included in all tools by jetbrains 

https://github.com/JetBrains/JetBrainsRuntime

An ebuild could be added for this java customization separately to be used by all Jetbrains tools

**Comment by lkraav** [comment]
I built PHP 7.4 with OpenSSL 3 patch you pointed out, so now I have no OpenSSL 1 traces on the systems. Everything seems to continue to work fine, PhpStorm default JBR boots fine.
![image](https://github.com/inode64/inode64-overlay/assets/147228/e1ba0529-cc46-45a1-b1d3-f8ab6c4da8df)

**Comment by inode64** [comment]
I'm glad everything works well,
I also have quite a few servers with old software
I only need the PHP 7.3 version because I have some Prestashop that do not work correctly with 7.4
As soon as I have some time I prepare the ebuild
