### ISSUE TITLE
app-misc/zigbee2mqtt-1.36.1: frontend does not load

### ISSUE THREAD

**Issue by daviessm** [inode64/inode64-overlay#21]
When connecting to the running Zigbee2MQTT instance it just displays the error `Error: ENOENT: no such file or directory, stat '/usr/lib64/node_modules/zigbee2mqtt/node_modules/zigbee2mqtt-frontend/dist/index.html.gz'`

There are, however, `index.html` and `index.html.br` in that directory.

**Comment by daviessm** [comment]
Digging into this, the previous zigbee2mqtt-1.36.0-node_modules.tar.xz contains index.com.gz but it's been replaced with index.com.br in the file from 1.36.1. I'm not sure how that archive is built though.

`zigbee2mqtt-1.36.1-node_modules.tar.xz\zigbee2mqtt-1.36.1-node_modules.tar\zigbee2mqtt-1.36.1\node_modules\zigbee2mqtt-frontend\dist\` is the directory in the archive.

**Comment by zen2** [comment]
.br extension stand for brotli compression using app-arch/brotli.

So it seems your web client is asking for a gzip accept-encoding and not a br one:

You can check br encoding support with:
`wget -SO /dev/null --header='Accept-Encoding: br' http://$DOMAIN/index.html`

Do you use a web proxy ? if yes you need to add brotli support.

**Comment by zen2** [comment]
I'm using a local install of  zigbee2mqtt-1.36.1 and not actually this ebuild and I got as you bare content along a .br version and no .gz one too.

My browser send a "Accept-Encoding: gzip, deflate, br" then receive an "Content-Encoding: br".

I see that I got this file on my install: node_modules/caniuse-lite/data/features/brotli.js

Do you find it on your side: `qlist app-misc/zigbee2mqtt | grep brotli.js`

**Comment by daviessm** [comment]
I do not! I have a lot of .br files but no brotli.js. Any idea where that should come from?

**Comment by inode64** [comment]
caniuse-lite is only used in developing Dependencies

If you send encoding in gzip it returns without encoding
Look at these tests

$ wget -SO /dev/null --header='Accept-Encoding: br' http://localhost:8081/index.html
<pre>
--2024-05-02 19:32:00--  http://localhost:8081/index.html
Resolviendo localhost (localhost)... 127.0.0.1
Conectando con localhost (localhost)[127.0.0.1]:8081... conectado.
Petición HTTP enviada, esperando respuesta... 
  HTTP/1.1 200 OK
  Content-Type: text/html; charset=UTF-8
  Content-Encoding: br
  Vary: Accept-Encoding
  Accept-Ranges: bytes
  Cache-Control: public, max-age=0
  Last-Modified: Thu, 02 May 2024 17:22:42 GMT
  ETag: W/"cc5-18f3a546e55"
  Content-Length: 3269
  Date: Thu, 02 May 2024 17:32:00 GMT
  Connection: keep-alive
  Keep-Alive: timeout=5
Longitud: 3269 (3,2K) [text/html]
</pre>

$ wget -SO /dev/null --header='Accept-Encoding: gzip' http://localhost:8081/index.html
<pre>
--2024-05-02 19:32:05--  http://localhost:8081/index.html
Resolviendo localhost (localhost)... 127.0.0.1
Conectando con localhost (localhost)[127.0.0.1]:8081... conectado.
Petición HTTP enviada, esperando respuesta... 
  HTTP/1.1 200 OK
  Cache-Control: no-store
  Accept-Ranges: bytes
  Last-Modified: Thu, 02 May 2024 17:22:42 GMT
  ETag: W/"13c6-18f3a546e55"
  Content-Type: text/html; charset=UTF-8
  Content-Length: 5062
  Date: Thu, 02 May 2024 17:32:05 GMT
  Connection: keep-alive
  Keep-Alive: timeout=5
Longitud: 5062 (4,9K) [text/html]
</pre>

$ wget -SO /dev/null --header='Accept-Encoding: gzip, br' http://localhost:8081/index.html
<pre>
--2024-05-02 19:32:21--  http://localhost:8081/index.html
Resolviendo localhost (localhost)... 127.0.0.1
Conectando con localhost (localhost)[127.0.0.1]:8081... conectado.
Petición HTTP enviada, esperando respuesta... 
  HTTP/1.1 200 OK
  Content-Type: text/html; charset=UTF-8
  Content-Encoding: br
  Vary: Accept-Encoding
  Accept-Ranges: bytes
  Cache-Control: public, max-age=0
  Last-Modified: Thu, 02 May 2024 17:22:42 GMT
  ETag: W/"cc5-18f3a546e55"
  Content-Length: 3269
  Date: Thu, 02 May 2024 17:32:21 GMT
  Connection: keep-alive
  Keep-Alive: timeout=5
Longitud: 3269 (3,2K) [text/html]
</pre>



Have you restarted after updating?
Because it seems that it cannot find the .gz file, this may happen because the previous version was used and now it is not, until you restart the daemon will not analyze the file structure again
I have found a hack to compress the files in .gz and so if you use an old browser, at least you will have a little compression

**Comment by daviessm** [comment]
I feel like an idiot. Restarting the service worked, it must not have been kicked since I updated.

Thanks for your help troubleshooting anyway!

**Comment by inode64** [comment]
I have also updated the ebuild to gzip the frontend to allow some compression on older systems in path a5884ea6cd8a545c309df51d446d3098a81f8f7f
